### ISSUE TITLE
Create tesseroid model does not work

### ISSUE THREAD

**Issue by nholz** [eldarbaykiev/magtess-inversion-python#1]
Creating a tesseroid model ends up with an error:
 
Traceback (most recent call last):
  File "gmi_gui.py", line 365, in CreateTesseroidModel
    import gmi_create_tesseroid_model
  File "/home/esasummer/MagInv/magtess-inversion-python/gmi_create_tesseroid_model.py", line 31
    else
       ^
SyntaxError: invalid syntax

**Comment by eldarbaykiev** [comment]
Fixed

**Comment by nholz** [comment]
Creating a tesseroid model ends up with an error:

Traceback (most recent call last):
  File "gmi_gui.py", line 365, in CreateTesseroidModel
    import gmi_create_tesseroid_model
  File "/home/esasummer/MagInv/magtess-inversion-python/gmi_create_tesseroid_model.py", line 12
    tar.extractfile()
                    ^
IndentationError: unindent does not match any outer indentation level
