### ISSUE TITLE
Create tesseroid model does not work 

### ISSUE THREAD

**Issue by nholz** [eldarbaykiev/magtess-inversion-python#3]
Gives an error, when trying to create a model: 
Traceback (most recent call last):
  File "gmi_gui.py", line 365, in CreateTesseroidModel
    import gmi_create_tesseroid_model
  File "/home/esasummer/MagInv/magtess-inversion-python/gmi_create_tesseroid_model.py", line 12
    tar.extractfile()
                    ^
IndentationError: unindent does not match any outer indentation level

**Comment by eldarbaykiev** [comment]
Fixed
