### ISSUE TITLE
Error during Tesseroid creation

### ISSUE THREAD

**Issue by nholz** [eldarbaykiev/magtess-inversion-python#4]
Traceback (most recent call last):
  File "gmi_gui.py", line 369, in CreateTesseroidModel
    import gmi_create_tesseroid_model
  File "/home/esasummer/MagInv/magtess-inversion-python/gmi_create_tesseroid_model.py", line 43
    if not os.path.isfile(gmi_config.IGRF_COEFF_FILENAME):
                                                         ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by eldarbaykiev** [comment]
fixed
