### ISSUE TITLE
File is missing ? 

### ISSUE THREAD

**Issue by nholz** [eldarbaykiev/magtess-inversion-python#5]
Do I have to provide a .magtess model ??
There is only a .tess model. 

Magnetic tesseroid model model.tess is created
Traceback (most recent call last):
  File "gmi_gui.py", line 382, in CreateTesseroidModel
    gmi_create_tesseroid_model.main(self.GMI_PATH)
  File "/home/esasummer/MagInv/magtess-inversion-python/gmi_create_tesseroid_model.py", line 119, in main
    with open(file_name, 'r') as file_to_check:
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: 'model.magtess'

**Comment by eldarbaykiev** [comment]
It's a linux related issue of permission on executables
